### ISSUE TITLE
Undo Bug

### ISSUE THREAD

**Issue by akanex115** [ajktown/wordnote#111]
# Background
When you click `undo` on word card, it DOES undo deletion (or post the word again), but it still shows the deleted word card component
<img width="883" alt="image" src="https://github.com/ajktown/wordnote/assets/128212558/e256950d-050b-4e6a-a896-aebb45a3e3be">
<img width="840" alt="image" src="https://github.com/ajktown/wordnote/assets/128212558/9727fb64-d179-4c25-8bab-bd59f3ad8817">

## TODOs
```
- [ ] Create activity diagram(s) associated to the bug
- [ ] Fix bug
```

**Comment by mlajkim** [comment]
Tip: 
```ts
// dialog is open, if selectedWordIdForDialogState is not null
// Why we've implemented this: https://github.com/ajktown/wordnote/issues/111
if (await snapshot.getPromise(selectedWordIdForDialogState)) {
  set(selectedWordIdForDialogState, postedWord.id)
}
```
