### ISSUE TITLE
Refresh bug

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#117]
# Background
When refresh button is clicked, it forces the latest semester

**How to reproduce the bug**
1. It requires at least two or more semesters
![image](https://github.com/ajktown/wordnote/assets/53258958/a9d266a5-0d59-4e79-8879-fccc25016708)

2. Click non latest semester (the example is 2023Y 4Q)
![image](https://github.com/ajktown/wordnote/assets/53258958/3ec731ce-51ab-448e-b6a1-c4cf0cca65f2)

3. Click refresh, and it becomes latest semester automatically
![image](https://github.com/ajktown/wordnote/assets/53258958/59f53fe7-b401-47b6-a82f-05a09c7bdb03)

## TODOs
- [x] Fix the bug

**Comment by akanex115** [comment]
TODOs
- [ ] refresh button をクリックしたら、同じセメスターのまま更新されるように実装する
