### ISSUE TITLE
Shared Word Card should show unclickable tags

### ISSUE THREAD

**Issue by mlajkim** [ajktown/wordnote#164]
### Background

Current shared word card does not show tags associated to the shared word card.
Should have it inside the red box, right next to the language tag (Japanese in this case)
![image](https://github.com/ajktown/wordnote/assets/53258958/a0fd1b7c-49ad-49a7-864d-0b9f500ec419)

### TODOs

```
- [ ] Implement unclickable tags for shared word card
```

**Comment by akanex115** [comment]
API does not respond tags for shared word
https://github.com/ajktown/api/blob/main/src/domains/word/index.interface.ts#L16

API must be modified too, if you want to show tags for shared word card

**Comment by mlajkim** [comment]
@akanex115 
thanks

handled in this PR https://github.com/ajktown/api/pull/79
can you check and merge it?
